### ISSUE TITLE
Solidify Game Design and plan

### ISSUE THREAD

**Issue by sh-biswas** [MLH-Fellowship/Evil-in-Jaffar#1]
**Is your feature request related to a problem? Please describe.**
We need to finalize our game idea + content, so we can document it here for open-sourcing.

**Describe the solution you'd like**
Here is what I have come up with. I have combined my game structure with Vividha's storyline:

 - Start scene: a discussion between 2 NPCs, one a wizard, and another a civilian. They discuss the kingdom and the dragon terrorizing the kingdom. They then talk about the prophecy of a knight saving the kingdom by slaying the dragon. It then cuts to the wizard NPC introducing the main player, who starts off as a lowly squire(with a small dagger). He tells him the prophecy and gives him instructions on how to go through the game, play the game, and become a knight to defeat the dragon. 

- Scene 1: First route - This will be the first route/level with the wizard introducing the first riddle. Squire solves the riddle, meets and fights the first boss, and gets an item that makes him level up(armor?).

- Scene 2: Second route - same thing as above, but next item to make him level up(sword?).

- Scene 3: Last route - same thing as above, but last item to level the squire up to a full knight. The knight then gets transported back to the kingdom.

- Last scene: Becoming a full knight unlocks the final boss the knight has to battle: the dragon. The knight battles the dragon, saves the kingdom, and concludes the game. 

**Describe alternatives you've considered**
Please leave any comments that suggest new storylines, additions to the game structure, additions to the storyline, confirm if you like this plan, etc. 

**Additional context**
After this is confirmed, we can go into the project board/issues and assign tasks.

**Comment by sh-biswas** [comment]
Level ups: Instead of material level ups, power level ups

**Comment by sh-biswas** [comment]
Idea: Eliminate riddles and get power from the boss once the boss is defeated

**Comment by sh-biswas** [comment]
Timeline idea:
 - start with basic game + defeat bosses
 - incorporate riddles later

**Comment by sh-biswas** [comment]
Instead of all 3 villains in routes: 
 - have different tasks in routes
    - find magical objects(by either retrieving from someone or defeating from someone), save someone, etc

**Comment by sh-biswas** [comment]
- Saurabh: Main character
 - Shilpita: Enemies + villains
 - Vividha: Backgrounds + other sprite-based assets

**Comment by V2dha** [comment]
Okay so plot is loosely based on the below story that we can basically use to create the game characters and scenes.

The story is set around the Middle Ages and starts with the birth of the emperor of Yemen's son **(Yemen is where the protagonist is born)** who is named **Protagonist of the game**, of whom is said that he will spread the message of peace and good. At the same time the son of the emperor of Jaffar **(Jaffar is where the antagonist is born)** is born, but due to black magic done by palace resident Najumi, it is said that the baby will be the greatest ever known servant of the evil spirits. The emperor of Jaffar then decides that it is better for the world that the baby is killed. The king orders that the baby's heart be burned; his man Najumi, who secretly serves the evil spirits, burns the heart of a rabbit instead and shows it to the emperor, leaving the emperor believing that the baby is dead. Najumi names the baby **Antagonist of the game** and teaches him all about the dark arts. Twenty years pass, **Protagonist** grows up into a kind-hearted, benevolent and beloved prince of Yemen, whereas in Jaffar, **Antagonist** deposes and kills his parents and becomes the emperor of Jaffar. He creates an eternal fire on the top tower of his palace that grants him dark powers. 

**The person who sets our protagonist on the quests** reveals that when **abode of good** was created by the forces of good, a prophecy was made that an evil lord will control this world as long as the angel of good doesn't intervene. **Protagonist** must solve the **quests /levels/ riddles/ obstacles... to be decided later**, to eliminate the power being given by dark forces to **Antagonist**, and for this purpose he must set off on a journey to distant lands and fantasy.

**Comment by sh-biswas** [comment]
Final Game Design Plan:
- 3 fighting scenes + opening scene
- Each scene has an automated villain
- Last scene is the final boss(Antagonist)
- Game plot derived from above storyline
